/** Textos y parámetros de interfaz. Preparado para i18n: añade idiomas en `strings`. */
export const UI = {
  defaultLanguage: 'es',
  strings: {
    es: {
      play: 'Jugar',
      settings: 'Ajustes',
      quit: 'Salir',
      findMatch: 'Buscar partida',
      createRoom: 'Crear sala',
      joinRoom: 'Unirse con código',
      buyMenu: 'Tienda',
      chooseTeam: 'Elige equipo',
      roundWon: '¡Ronda ganada!',
      roundLost: 'Ronda perdida',
      bombPlanted: '¡Bomba plantada!',
      bombDefused: '¡Bomba desactivada!',
      connecting: 'Conectando…',
      disconnected: 'Desconectado del servidor',
      serverOffline: 'No hay servidor de juego en {url}. Arráncalo con: npm run dev:server',
      serverChecking: 'Comprobando servidor…',
      serverReady: 'Servidor listo',
      roomNotFound: 'No existe una sala con ese código',
      roomFull: 'Esa sala está llena',
      joinFailed: 'No se pudo entrar a la partida: {detail}',
      versionMismatch: 'Tu versión del juego no coincide con la del servidor. Recarga la página.',
    },
    en: {
      play: 'Play',
      settings: 'Settings',
      quit: 'Quit',
      findMatch: 'Find match',
      createRoom: 'Create room',
      joinRoom: 'Join with code',
      buyMenu: 'Shop',
      chooseTeam: 'Choose team',
      roundWon: 'Round won!',
      roundLost: 'Round lost',
      bombPlanted: 'Bomb planted!',
      bombDefused: 'Bomb defused!',
      connecting: 'Connecting…',
      disconnected: 'Disconnected from server',
      serverOffline: 'No game server at {url}. Start it with: npm run dev:server',
      serverChecking: 'Checking server…',
      serverReady: 'Server ready',
      roomNotFound: 'No room with that code',
      roomFull: 'That room is full',
      joinFailed: 'Could not join the match: {detail}',
      versionMismatch: 'Your game version does not match the server. Reload the page.',
    },
  },
  hud: {
    crosshairSize: 8,
    crosshairColor: '#ffffff',
    hitmarkerDuration: 0.12,
    killfeedMax: 5,
    killfeedDuration: 6,
  },
} as const;
export type Language = keyof typeof UI.strings;
export type StringKey = keyof typeof UI.strings.es;
